apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app # Links to the deployment by label
  type: NodePort # Exposes the service on a port on each node (Minikube VM)
  ports:
  - protocol: TCP
    port: 80 # The port the service will listen on (standard HTTP)
    targetPort: 5000 # The port the container is listening on